# Generated by Django 4.1.4 on 2022-12-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tk_database', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='image',
            field=models.FilePathField(blank=True, default=None, null=True),
        ),
    ]
