# Generated by Django 4.1.4 on 2022-12-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tk_database', '0003_alter_hike_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='hike_pics'),
        ),
    ]
