# Generated by Django 4.1.4 on 2022-12-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tk_database', '0004_alter_hike_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='is_full',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
