# Generated by Django 4.1.4 on 2022-12-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tk_database', '0005_hike_is_full'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hike',
            old_name='GeoRegion',
            new_name='region',
        ),
    ]
